export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR';

export const USER_SIGNUP_REQUEST = 'USER_SIGNUP_REQUEST';
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
export const USER_SIGNUP_ERROR = 'USER_SIGNUP_ERROR';

export const USER_BLOG_REQUEST = 'USER_BLOG_REQUEST';
export const USER_BLOG_SUCCESS = 'USER_BLOG_SUCCESS';
export const USER_BLOG_ERROR = 'USER_BLOG_ERROR';

export const POST_REQUEST = 'POST_REQUEST';
export const POST_SUCCESS = 'POST_SUCCESS';
export const POST_ERROR = 'POST_ERROR';

export const POST_API_REQUEST = 'POST_API_REQUEST';
export const POST_API_SUCCESS = 'POST_API_SUCCESS';
export const POST_API_ERROR = 'POST_API_ERROR';
export const POST_API_CLEAR = 'POST_API_CLEAR';
